/*  ===========================================================
     
    This code is auto generated and should not be modified
    This is definition of class for rendering "Basic"
    Code was generated by ViewEngine
    Version 1.0 - 2018
    
    ===========================================================
*/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ViewEngine.Core.Engine;
using System.Web.Mvc;

// Additional Namespaces
// =====================
namespace ViewEngine.IntegratedTests
{
    // BasicView - generated class which
    // should be used for rendering views
    [ViewRenderer(@"C:\magisterium\ViewEngine\ViewEngine.IntegratedTests\Basic\Basic.myview")]
    class BasicView : IView
    {
        // SECTION WITH MIXIN DECLARATIONS ======
        public static void Basic(TextWriter writer)
        {
            writer.Write(@"Witaj świecie!!!");
            writer.Write("\r\n");
        }

        // END OF SECTION WITH MIXIN DECLARATIONS
        // ======================================
        // Render Method
        public void Render(ViewContext viewContext, TextWriter writer)
        {
            Basic(writer);
        }
    }
}