/*  ===========================================================
     
    This code is auto generated and should not be modified
    This is definition of class for rendering "Index"
    Code was generated by ViewEngine
    Version 1.0 - 2018
    
    ===========================================================
*/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ViewEngine.Core.Engine;
using System.Web.Mvc;

// Additional Namespaces
// =====================
namespace SampleWebApplication.Views
{
    // IndexView - generated class which
    // should be used for rendering views
    [ViewRenderer(@"E:\kodzenie\mgr\final\ViewEngine.Core\ViewEngine\SampleWebApplication\Views\Home\Index.myview")]
    class IndexView : IView
    {
        // SECTION WITH MIXIN DECLARATIONS ======
        // END OF SECTION WITH MIXIN DECLARATIONS
        // ======================================
        // Render Method
        public void Render(ViewContext viewContext, TextWriter writer)
        {
            CommonHelper.Html(writer, () =>
            {
                writer.Write(@"Przyklad strony logowania");
            }

            , () =>
            {
                CommonHelper.H1(writer, () =>
                {
                    writer.Write(@"Strona logowania");
                }

                );
                CommonHelper.Line(writer, () =>
                {
                    writer.Write(@"Podaj dane do logowania");
                }

                );
                CommonHelper.Form(writer, "Home", "Index", () =>
                {
                    CommonHelper.Table(writer, () =>
                    {
                        CommonHelper.Tr(writer, () =>
                        {
                            CommonHelper.Td(writer, () =>
                            {
                                writer.Write(@"Name: ");
                            }

                            );
                            CommonHelper.Td(writer, () =>
                            {
                                CommonHelper.TextInput(writer, "Name");
                            }

                            );
                        }

                        );
                        CommonHelper.Tr(writer, () =>
                        {
                            CommonHelper.Td(writer, () =>
                            {
                                writer.Write(@"Password: ");
                            }

                            );
                            CommonHelper.Td(writer, () =>
                            {
                                CommonHelper.PassInput(writer, "Password");
                            }

                            );
                        }

                        );
                    }

                    );
                    CommonHelper.Submit(writer, "Logowanie");
                }

                );
            }

            );
        }
    }
}