/*  ===========================================================
     
    This code is auto generated and should not be modified
    This is definition of class for rendering "Basic2"
    Code was generated by ViewEngine
    Version 1.0 - 2018
    
    ===========================================================
*/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ViewEngine.Core.Engine;
using System.Web.Mvc;
// Additional Namespaces
using System.IO;

// =====================
namespace ViewEngine.IntegratedTests
{
    // Basic2View - generated class which
    // should be used for rendering views
    [ViewRenderer(@"E:\kodzenie\mgr\final\ViewEngine.Core\ViewEngine\ViewEngine.IntegratedTests\Basic2\Basic2.myview")]
    class Basic2View : IView
    {
        // SECTION WITH MIXIN DECLARATIONS ======
        public static void P(TextWriter writer, Action content)
        {
            writer.Write(@"<p> ");
            content();
            writer.Write(@" </p>");
            writer.Write("\r\n");
        }

        // END OF SECTION WITH MIXIN DECLARATIONS
        // ======================================
        // Render Method
        public void Render(ViewContext viewContext, TextWriter writer)
        {
            Action dir = () =>
            {
                writer.Write($"{Directory.GetCurrentDirectory()}");
            }

            ;
            P(writer, () =>
            {
                dir();
            }

            );
        }
    }
}