using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ViewEngine.Core.Engine;

namespace ViewEngine.Example
{
    public class Program
    {
        public static void Main()
        {
            // Example of using Core Engine
            var engine = new CoreEngine();
            engine.Render("Main", "ViewEngine.Example",
                "Views\\MainView.view", new [] {"Views\\Common.helper"}, "MainViewRenderer.cs");


            // Example of using class which was generated by
            // Core Engine
            var model = new ExampleModel
            {
                Name = "Marek"
            };
            //var renderManager = new MainRenderManager();
            var output = new StreamWriter("out.html");
            //renderManager.Render(output, model);
            output.Close();
        }
    }
}
