/*  ===========================================================
     
    This code is auto generated and should not be modified
    This is definition of class with helping mixins "Common"
    Code was generated by ViewEngine
    Version 1.0 - 2018
    
    ===========================================================
*/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ViewEngine.Core.Engine;

// Additional Namespaces
// =====================
namespace SampleWebApplication.Views
{
    public static class CommonHelper
    {
        public static void Html(TextWriter writer, Action title, Action body)
        {
            writer.Write(@"<html>");
            writer.Write("\r\n");
            writer.Write(@"<head>");
            writer.Write("\r\n");
            writer.Write(@"<title>");
            writer.Write("\r\n");
            title();
            writer.Write("\r\n");
            writer.Write(@"</title>");
            writer.Write("\r\n");
            writer.Write(@"</head>");
            writer.Write("\r\n");
            writer.Write(@"<body>");
            writer.Write("\r\n");
            body();
            writer.Write("\r\n");
            writer.Write(@"</body>");
            writer.Write("\r\n");
            writer.Write(@"</html>");
            writer.Write("\r\n");
        }

        public static void H1(TextWriter writer, Action header)
        {
            writer.Write(@"<h1> ");
            header();
            writer.Write(@" </h1>");
            writer.Write("\r\n");
        }

        public static void Line(TextWriter writer, Action line)
        {
            line();
            writer.Write(@" </br>");
            writer.Write("\r\n");
        }

        public static void Form(TextWriter writer, string actionName, string controllerName, Action body)
        {
            writer.Write(@"<form action=""/");
            writer.Write($"{controllerName}");
            writer.Write(@"/");
            writer.Write($"{actionName}");
            writer.Write(@""" method=""post"">");
            writer.Write("\r\n");
            body();
            writer.Write("\r\n");
            writer.Write(@"</form>");
            writer.Write("\r\n");
        }

        public static void Input(TextWriter writer, string name)
        {
            writer.Write(@"<input id=""");
            writer.Write($"{name}");
            writer.Write(@""" name=""");
            writer.Write($"{name}");
            writer.Write(@""" type=""text"" value="""">");
            writer.Write("\r\n");
        }
    }
}