/*  ===========================================================
     
    This code is auto generated and should not be modified
    This is definition of class with helping mixins "Common"
    Code was generated by ViewEngine
    Version 1.0 - 2018
    
    ===========================================================
*/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ViewEngine.Core.Engine;

// Additional Namespaces
// =====================
namespace SampleWebApplication.Views
{
    public static class CommonHelper
    {
        public static void Html(TextWriter writer, Action title, Action body)
        {
            writer.Write(@"<html>");
            writer.Write("\r\n");
            writer.Write(@"<head>");
            writer.Write("\r\n");
            writer.Write(@"<title>");
            writer.Write("\r\n");
            title();
            writer.Write("\r\n");
            writer.Write(@"</title>");
            writer.Write("\r\n");
            writer.Write(@"</head>");
            writer.Write("\r\n");
            writer.Write(@"<body>");
            writer.Write("\r\n");
            body();
            writer.Write("\r\n");
            writer.Write(@"</body>");
            writer.Write("\r\n");
            writer.Write(@"</html>");
            writer.Write("\r\n");
        }

        public static void H1(TextWriter writer, Action header)
        {
            writer.Write(@"<h1> ");
            header();
            writer.Write(@" </h1>");
            writer.Write("\r\n");
        }

        public static void H2(TextWriter writer, Action header)
        {
            writer.Write(@"<h2> ");
            header();
            writer.Write(@" </h2>");
            writer.Write("\r\n");
        }

        public static void H3(TextWriter writer, Action header)
        {
            writer.Write(@"<h3> ");
            header();
            writer.Write(@" </h3>");
            writer.Write("\r\n");
        }

        public static void Line(TextWriter writer, Action line)
        {
            line();
            writer.Write(@" </br>");
            writer.Write("\r\n");
        }

        public static void Form(TextWriter writer, string controllerName, string actionName, Action body)
        {
            writer.Write(@"<form action=""/");
            writer.Write($"{controllerName}");
            writer.Write(@"/");
            writer.Write($"{actionName}");
            writer.Write(@""" method=""post"">");
            writer.Write("\r\n");
            body();
            writer.Write("\r\n");
            writer.Write(@"</form>");
            writer.Write("\r\n");
        }

        public static void TextInput(TextWriter writer, string name)
        {
            writer.Write(@"<input id=""");
            writer.Write($"{name}");
            writer.Write(@""" name=""");
            writer.Write($"{name}");
            writer.Write(@""" type=""text"" value="""">");
            writer.Write("\r\n");
        }

        public static void PassInput(TextWriter writer, string name)
        {
            writer.Write(@"<input id=""");
            writer.Write($"{name}");
            writer.Write(@""" name=""");
            writer.Write($"{name}");
            writer.Write(@""" type=""password"" value="""">");
            writer.Write("\r\n");
        }

        public static void Td(TextWriter writer, Action body)
        {
            writer.Write(@"<td> ");
            body();
            writer.Write(@" </td>");
            writer.Write("\r\n");
        }

        public static void Tr(TextWriter writer, Action body)
        {
            writer.Write(@"<tr> ");
            body();
            writer.Write(@" </tr>");
            writer.Write("\r\n");
        }

        public static void Table(TextWriter writer, Action body)
        {
            writer.Write(@"<table cellpadding=""0"" cellspacing=""0"">");
            writer.Write("\r\n");
            writer.Write(@"<tbody>");
            writer.Write("\r\n");
            body();
            writer.Write("\r\n");
            writer.Write(@"</tbody>");
            writer.Write("\r\n");
            writer.Write(@"</table>");
            writer.Write("\r\n");
        }

        public static void Submit(TextWriter writer, string name)
        {
            writer.Write(@"<input type=""submit"" value=""");
            writer.Write($"{name}");
            writer.Write(@""">");
            writer.Write("\r\n");
        }

        public static void Ul(TextWriter writer, Action body)
        {
            writer.Write(@"<ul> ");
            body();
            writer.Write(@" </ul>");
            writer.Write("\r\n");
        }

        public static void Li(TextWriter writer, Action body)
        {
            writer.Write(@"<li> ");
            body();
            writer.Write(@" </li>");
            writer.Write("\r\n");
        }

        public static void P(TextWriter writer, Action body)
        {
            writer.Write(@"<p> ");
            body();
            writer.Write(@" </p>");
            writer.Write("\r\n");
        }

        public static void If(TextWriter writer, bool condition, Action trueState, Action falseState)
        {
            if (condition)
            {
                trueState();
            }
            else
            {
                falseState();
            }
        }
    }
}